server:
  port: 8761  # Default : 8761

spring:
  application:
    name: eureka

eureka:
    server:
      response-cache-update-interval-ms: 3000 # Eureka Server's Response Cache. Default 30,000ms
      enableSelfPreservation: false           # Just for demo
    client:
      register-with-eureka: false             # Only for local stand-alone development
      fetch-registry: false                   # Only for local stand-alone development
      service-url:
        defaultZone: http://localhost:8761/eureka  # Default Value. 다른 서버에 있을때 반드시 설정
    instance:
      prefer-ip-address: true                 # Use ip address instead of hostname from OS when reporting myself to eureka server