server:
  port: 8083

spring:
  application:
    name: command    # Eureka Client가 Eureka Server에 자신을 등록할때 이 이름으로 등록됨
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017
      database: MyDatabase
  # set h2 properties
  # 사실 path는 h2이 기본 path 이다. 바꾸고 싶다면 바꾸어주자
  h2:
    console:
      enabled : true
      path : /h2
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.hbm2ddl.auto: update
    showSql: true


eureka:
  instance:
    prefer-ip-address: true  # 로컬에서 ip로 테스트 하기 위해
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka  # default address

logging.level.com.prugio.command : debug

